services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: bodygraph
    working_dir: /app
    command: npm start
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
